### PR TITLE
memfs: Add thread-safety to Memory

### LINKED ISSUE #40: Creating new files is not multi-goroutine safe
If you call `New()` on the `storage` objects from multiple goroutines at the same time, go runtime may error with `fatal error: concurrent map writes`. This happens because the `files` map inside the `storage` struct has no concurrency protection around multiple access.

Other concurrency issues probably exist for accessing the `children` map inside the `storage` object.

### PR DESCRIPTION
**Pull request by pjbgf**
Make `Memory` thread-safe for operations such as `Create`, `Rename` and `Delete`. When compared with `Memory` without a mutex, the cost per op is roughly `50ns`, as per benchmark below:

```
goos: linux
goarch: amd64
pkg: github.com/go-git/go-billy/v6/test
cpu: AMD Ryzen 7 PRO 8840HS w/ Radeon 780M Graphics
BenchmarkCompare/stdlib_open-16         	  341277	      3303 ns/op	     152 B/op	       3 allocs/op
BenchmarkCompare/osfs.chrootOS_open-16  	  286580	      3806 ns/op	     360 B/op	       9 allocs/op
BenchmarkCompare/osfs.boundOS_open-16   	  209929	      5311 ns/op	     984 B/op	      20 allocs/op
BenchmarkCompare/memfs_open-16          	 1503024	       967.4 ns/op	     224 B/op	      10 allocs/op
BenchmarkCompare/memfs_mutex_open-16    	 1272890	       911.6 ns/op	     224 B/op	      10 allocs/op
BenchmarkCompare/stdlib_read-16         	  184956	      5957 ns/op	 171.88 MB/s	       0 B/op	       0 allocs/op
BenchmarkCompare/osfs.chrootOS_read-16  	  180552	      6207 ns/op	 164.97 MB/s	       0 B/op	       0 allocs/op
BenchmarkCompare/osfs.boundOS_read-16   	  179314	      6131 ns/op	 167.02 MB/s	       0 B/op	       0 allocs/op
BenchmarkCompare/memfs_read-16          	  792040	      1568 ns/op	 653.02 MB/s	       0 B/op	       0 allocs/op
BenchmarkCompare/memfs_mutex_read-16    	  783422	      1609 ns/op	 636.27 MB/s	       0 B/op	       0 allocs/op
BenchmarkCompare/stdlib_create-16       	  216717	      5232 ns/op	     152 B/op	       3 allocs/op
BenchmarkCompare/osfs.chrootOS_create-16         	  157268	      7017 ns/op	     616 B/op	      11 allocs/op
BenchmarkCompare/osfs.boundOS_create-16          	  123038	      9242 ns/op	    1335 B/op	      22 allocs/op
BenchmarkCompare/memfs_create-16                 	  880813	      1954 ns/op	     693 B/op	      12 allocs/op
BenchmarkCompare/memfs_mutex_create-16           	  559534	      1901 ns/op	     631 B/op	      12 allocs/op
PASS
ok  	github.com/go-git/go-billy/v6/test	118.368s
```

Some minor changes to `Rename` were made on `osfs` implementations, to ensure consistent behaviour across the built-in
implementations.

Additional thread-safety will be required for `memfs.file`, which will be dealt with separately.

Closes #40.
Relatest to https://github.com/go-git/go-git/issues/773.

PS: The benchmark results were based before the removal of the Mutex option (last commit).

### CODE REVIEW

File: memfs/memory.go [hunk 1]
```diff
@@ -24,11 +22,25 @@ const separator = filepath.Separator
 // Memory a very convenient filesystem based on memory files.
 type Memory struct {
 	s *storage
+
+	m mutex
```
Comment (aymanbagabas) [inline memfs/memory.go:26]: Why not `sync.RWMutext`?
```suggestion
	m sync.RWMutext
```

File: memfs/memory.go [hunk 2]
```diff
@@ -24,11 +22,25 @@ const separator = filepath.Separator
...
 }
 
 // New returns a new Memory filesystem.
-func New() billy.Filesystem {
-	fs := &Memory{s: newStorage()}
+func New(opts ...Option) billy.Filesystem {
+	o := &options{
+		// Enable thread-safety by default.
+		newMutex: newMutex,
+	}
```
Comment (aymanbagabas) [inline memfs/memory.go:34]: I think we should always enable thread-safety

File: memfs/memory.go [hunk 3]
```diff
@@ -23,23 +24,19 @@ const separator = filepath.Separator
...
+	m sync.RWMutex
 }
 
 // New returns a new Memory filesystem.
 func New(opts ...Option) billy.Filesystem {
-	o := &options{
-		// Enable thread-safety by default.
-		newMutex: newMutex,
-	}
-
```
Comment (aymanbagabas) [inline memfs/memory.go]: Do we need `opts ...Option` and `options`?

File: memfs/memory.go [hunk 4]
```diff
@@ -24,11 +23,21 @@ const separator = filepath.Separator
...
-	fs := &Memory{s: newStorage()}
+func New(opts ...Option) billy.Filesystem {
+	o := &options{}
+	for _, opt := range opts {
+		opt(o)
+	}
+
+	fs := &Memory{
+		s: newStorage(),
+		m: sync.RWMutex{},
```
Comment (aymanbagabas) [inline memfs/memory.go:39]: This can be omitted 
```suggestion
```

File: memfs/memory_option.go [hunk 5]
```diff
@@ -0,0 +1,6 @@
+package memfs
+
+type Option func(*options)
+
+type options struct {
+}
```
Comment (aymanbagabas) [inline memfs/memory_option.go:6]: We can remove this altogether
```suggestion
```

File: memfs/memory.go [hunk 6]
```diff
@@ -24,11 +23,21 @@ const separator = filepath.Separator
...
 }
 
 // New returns a new Memory filesystem.
-func New() billy.Filesystem {
-	fs := &Memory{s: newStorage()}
+func New(opts ...Option) billy.Filesystem {
+	o := &options{}
+	for _, opt := range opts {
+		opt(o)
+	}
```
Comment (aymanbagabas) [inline memfs/memory.go:35]:
```suggestion
func New() billy.Filesystem {
```

File: memfs/memory_option.go (hunk 5 above)
Comment (pjbgf) [reply memfs/memory_option.go:6]: I left this on purpose, the idea is to add additional options on a follow-up PR. Please note that the pattern aligns with both osfs implementations.

File: memfs/memory.go (hunk 4 above)
Comment (pjbgf) [reply memfs/memory.go:39]: Good shout, let me amend that.

File: memfs/memory.go (hunk 3 above)
Comment (pjbgf) [reply memfs/memory.go]: Yes, the plan is to align with the other osfs implementations in a future PR.
